[package]
name = "zklash"
authors = [""]
compiler_version = "0.10.1"
type = "bin"

[dependencies]
ecrecover = {tag = "v0.10.1", git = "https://github.com/colinnielsen/ecrecover-noir"}
array_helpers = { tag = "v0.10.0", git = "https://github.com/colinnielsen/noir-array-helpers" }
